import esbuild from "esbuild";
import { createPrivateKey, createPublicKey } from "node:crypto";
import { copyFile, mkdir, rm } from "node:fs/promises";
import { join, resolve } from "node:path";

const isRelease = process.argv.includes("--release");
const validateGuideFeedOnly = process.argv.includes("--validate-guide-feed-only");
const outputDirectory = isRelease ? "release" : ".";
const runtimePublicKey = process.env.CHATOBBY_RUNTIME_PUBLIC_KEY?.trim() ?? "";
const developmentGuideFeedBaseUrl = validateDevelopmentGuideFeedBaseUrl(
  process.env.CHATOBBY_DEV_GUIDE_FEED_BASE_URL,
  runtimePublicKey,
  isRelease,
);
const automaticRuntimeProvisioning =
  process.env.CHATOBBY_OBSIDIAN_APPROVED_AUTOMATIC_RUNTIME_PROVISIONING === "1";

if (isRelease && !runtimePublicKey) {
  throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY is required for a release build");
}

if (validateGuideFeedOnly) {
  process.stdout.write(`${JSON.stringify({ developmentGuideFeedBaseUrl })}\n`);
  process.exit(0);
}

if (isRelease) {
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
}

// Two independent bundles built concurrently:
//   - main.js     : the plugin (CJS, Obsidian's loader)
//   - styles.css  : every component's co-located CSS (src/ui/**) concatenated
//                   from the src/ui/styles.css barrel, written to the root
//                   styles.css Obsidian loads. Edit component CSS in place;
//                   this regenerates the root file on every build.
await Promise.all([
  esbuild.build({
    entryPoints: ["src/main.ts"],
    bundle: true,
    alias: {
      "@chatobby/obsidian-protocol": resolve("src/vendor/@chatobby/obsidian-protocol/index.ts"),
      "@chatobby/project-contracts": resolve("src/vendor/@chatobby/project-contracts/index.ts"),
    },
    external: [
      "obsidian",
      "electron",
      "@codemirror/*",
      "@lezer/*",
      // NOTE: @chatobby/chatobby/client is NOT external — the browser-safe client
      // SDK is vendored under src/vendor/chatobby-client/ and bundled into main.js.
      // NOTE: @chatobby/obsidian-protocol is NOT external — it is runtime-vendored
      // into src/vendor/@chatobby/obsidian-protocol/ and bundled into main.js.
      // See CLAUDE.md "runtime-vendored (browser-safe)" consumption class.
      // Agent/message/event domain types live in src/types/agent.ts (plugin-owned);
      // there is no @earendil-works/* runtime dependency anymore.
    ],
    format: "cjs",
    platform: "node",
    target: "es2022",
    outfile: join(outputDirectory, "main.js"),
    banner: {
      js: developmentGuideFeedBaseUrl ? "/* CHATOBBY_DEV_GUIDE_FEED_OVERRIDE_V1 */" : "",
    },
    sourcemap: isRelease ? false : "inline",
    minify: isRelease,
    legalComments: "eof",
    define: {
      __CHATOBBY_BUILD_MODE__: JSON.stringify(isRelease ? "release" : "development"),
      __CHATOBBY_RUNTIME_PUBLIC_KEY__: JSON.stringify(runtimePublicKey),
      __CHATOBBY_AUTOMATIC_RUNTIME_PROVISIONING__: JSON.stringify(
        isRelease && automaticRuntimeProvisioning,
      ),
      __CHATOBBY_DEV_GUIDE_FEED_BASE_URL__: JSON.stringify(developmentGuideFeedBaseUrl),
    },
    drop: isRelease ? ["debugger"] : [],
    logLevel: "info",
  }),
  esbuild.build({
    entryPoints: ["src/ui/styles.css"],
    bundle: true, // inlines @import from the component CSS files
    outfile: join(outputDirectory, "styles.css"),
    loader: { ".css": "css" },
    minify: isRelease,
    banner: { css: "/* GENERATED by esbuild from src/ui/styles.css — edit component CSS files, not this file. */" },
    logLevel: "info",
  }),
]);

if (isRelease) {
  await copyFile("manifest.json", join(outputDirectory, "manifest.json"));
}

function validateDevelopmentGuideFeedBaseUrl(value, trustedPublicKey, releaseBuild) {
  const candidate = value?.trim() ?? "";
  if (!candidate) return "";
  if (releaseBuild) {
    throw new Error("CHATOBBY_DEV_GUIDE_FEED_BASE_URL is forbidden in a release build");
  }
  if (!trustedPublicKey) {
    throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY is required for a development Guide feed");
  }
  let containsPrivateKey = false;
  try {
    createPrivateKey(trustedPublicKey);
    containsPrivateKey = true;
  } catch {
    // Expected for a public-only SPKI value.
  }
  if (containsPrivateKey) {
    throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY must not contain private key material");
  }
  let key;
  try {
    key = createPublicKey(trustedPublicKey);
  } catch {
    throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY must contain a valid Ed25519 public key");
  }
  if (key.asymmetricKeyType !== "ed25519") {
    throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY must contain a valid Ed25519 public key");
  }

  let url;
  try {
    url = new URL(candidate);
  } catch {
    throw new Error("CHATOBBY_DEV_GUIDE_FEED_BASE_URL must be an absolute loopback HTTPS URL");
  }
  if (
    url.protocol !== "https:" ||
    (url.hostname !== "localhost" && url.hostname !== "127.0.0.1") ||
    url.username ||
    url.password ||
    url.search ||
    url.hash ||
    !url.pathname.endsWith("/")
  ) {
    throw new Error(
      "CHATOBBY_DEV_GUIDE_FEED_BASE_URL must be a credential-free localhost or 127.0.0.1 HTTPS directory URL ending in /",
    );
  }
  return url.toString();
}
