import esbuild from "esbuild";
import { copyFile, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";

const isRelease = process.argv.includes("--release");
const outputDirectory = isRelease ? "release" : ".";
const runtimePublicKey = process.env.CHATOBBY_RUNTIME_PUBLIC_KEY?.trim() ?? "";

if (isRelease && !runtimePublicKey) {
  throw new Error("CHATOBBY_RUNTIME_PUBLIC_KEY is required for a release build");
}

if (isRelease) {
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
}

// Two independent bundles built concurrently:
//   - main.js     : the plugin (CJS, Obsidian's loader)
//   - styles.css  : every component's co-located CSS (src/ui/**) concatenated
//                   from the src/ui/styles.css barrel, written to the root
//                   styles.css Obsidian loads. Edit component CSS in place;
//                   this regenerates the root file on every build.
await Promise.all([
  esbuild.build({
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
      "obsidian",
      "electron",
      "@codemirror/*",
      "@lezer/*",
      // NOTE: @chatobby/chatobby/client is NOT external — the browser-safe client
      // SDK is vendored under src/vendor/chatobby-client/ and bundled into main.js.
      // NOTE: @chatobby/obsidian-protocol is NOT external — it is runtime-vendored
      // into src/vendor/@chatobby/obsidian-protocol/ and bundled into main.js.
      // See CLAUDE.md "runtime-vendored (browser-safe)" consumption class.
      // Agent/message/event domain types live in src/types/agent.ts (plugin-owned);
      // there is no @earendil-works/* runtime dependency anymore.
    ],
    format: "cjs",
    platform: "node",
    target: "es2022",
    outfile: join(outputDirectory, "main.js"),
    sourcemap: isRelease ? false : "inline",
    minify: isRelease,
    legalComments: "eof",
    define: {
      __CHATOBBY_BUILD_MODE__: JSON.stringify(isRelease ? "release" : "development"),
      __CHATOBBY_RUNTIME_PUBLIC_KEY__: JSON.stringify(runtimePublicKey),
    },
    drop: isRelease ? ["debugger"] : [],
    logLevel: "info",
  }),
  esbuild.build({
    entryPoints: ["src/ui/styles.css"],
    bundle: true, // inlines @import from the component CSS files
    outfile: join(outputDirectory, "styles.css"),
    loader: { ".css": "css" },
    minify: isRelease,
    banner: { css: "/* GENERATED by esbuild from src/ui/styles.css — edit component CSS files, not this file. */" },
    logLevel: "info",
  }),
]);

if (isRelease) {
  await copyFile("manifest.json", join(outputDirectory, "manifest.json"));
}
